import { describe, expect, it } from "vitest";
import { processMarkdown } from "../../../src/markdown/processor";
import { exportHtmlDocument } from "../../../src/services/export";

describe("untrusted Markdown styles", () => {
  it("removes overlay CSS from raw HTML in the shared preview/export pipeline", async () => {
    const source = '<span style="position:fixed;inset:0;z-index:9999;background:red">overlay</span>\n\n' +
      '<pre style="position:fixed"><code style="z-index:9999">text</code></pre>';
    const preview = (await processMarkdown(source)).html;
    const exported = await exportHtmlDocument(source);
    for (const html of [preview, exported.split("<body>")[1]]) {
      expect(html).toContain("overlay");
      expect(html).not.toMatch(/position\s*:|inset\s*:|z-index\s*:|background\s*:/i);
      expect(html).not.toContain('style="');
    }
  });

  it("does not trust spoofed Shiki classes or CSS-variable functions", async () => {
    const html = (await processMarkdown('<span class="shiki" style="--shiki-light:var(--evil);position:fixed">text</span>')).html;
    expect(html).not.toContain('style="');
  });

  it("preserves Shiki's generated literal token colors", async () => {
    const html = (await processMarkdown("```javascript\nconst answer = 42\n```")).html;
    expect(html).toContain('class="shiki shiki-themes catppuccin-latte catppuccin-mocha"');
    expect(html).toMatch(/--shiki-light:#[0-9a-fA-F]{3,8}/);
    expect(html).toMatch(/--shiki-dark:#[0-9a-fA-F]{3,8}/);
  });

  it("preserves layout styles generated by trusted KaTeX", async () => {
    const html = (await processMarkdown("$\\frac{1}{2}$")).html;
    expect(html).toContain("katex");
    expect(html).toMatch(/style="[^"]*(?:height|vertical-align):/);
  });
});
